version: "3.7"

services:

  php-cli:
    build:
      context: ./docker/php-cli
    working_dir: /var/www
    volumes:
      - ./:/var/www/
    depends_on:
      - mysql
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE}
      XDEBUG_SESSION: ${XDEBUG_SESSION}
      XDEBUG_CONFIG: "client_host=${XDEBUG_CLIENT_HOST} client_port=${XDEBUG_CLIENT_PORT} output_dir=${XDEBUG_OUTPUT_DIR}"
      PHP_IDE_CONFIG: serverName=${PHP_IDE_CONFIG_SERVER_NAME}
      COMPOSER_AUTH: ${COMPOSER_AUTH}

  composer:
    build:
      context: ./docker/composer
    working_dir: /var/www
    volumes:
      - ./:/var/www/
    depends_on:
      - mysql
    environment:
      - COMPOSER_AUTH=${COMPOSER_AUTH}


  mysql:
    image: mysql:5.7.13
    #    позволяет подлкючиться через свой mysql
    #    command: --default-authentication-plugin=mysql_native_password
    working_dir: /var/www
    volumes:
      - ./docker/storage/mysql/seeds:/docker-entrypoint-initdb.d
    #      - mysql-data:/var/lib/mysql/data
    ports:
      - ${HOST_MYSQL_PORT}:${DEFAULT_MYSQL_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_ROOT_HOST=host.docker.inernal
